version: '2'
services:
  influxdb:
    image: influxdb:1.0
    container_name: influxdb
    ports:
      - '8086:8086'
      - '8083:8083'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db1
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
        GF_SECURITY_ADMIN_USER: 'admin'
        GF_SECURITY_ADMIN_PASSWORD: 'admin'
volumes:
    influxdb-storage:
    grafana-storage:
