version: '2' #docker sürümüne göre version numarasını seçiyoruz. Detaylı version bilgileri için https://docs.docker.com/compose/compose-file/compose-versioning/ adresini ziyaret ediniz.
services:
  influxdb:
    image: influxdb:1.0 #influxdb'nin 1.0 olan sürümünü yükler.
    container_name: influxdb
    ports:
      #influxdb sayfasının gelmesi için aşağıdaki portları tanımlamamız gerekmektedir.
      - '8086:8086' 
      - '8083:8083'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db1 #db1 adında yeni bir database oluşturuyor.
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000' #grafana sayfasının gelmesi için '3000' portunu tanımlamamız gerekmektedir.
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
        #grafana için default olarak gelen kullanıcı adı ve password. (admin)
        GF_SECURITY_ADMIN_USER: 'admin'
        GF_SECURITY_ADMIN_PASSWORD: 'admin'
volumes:
    influxdb-storage:
    grafana-storage:
